const wordData = [
  { word: "翻", meaning: "to flip; to turn over", example: "請把書翻到第三十頁。(Please turn the book to page 30.)" },
  { word: "頁", meaning: "page", example: "這一頁有新的文法。(This page has new grammar.)" },
  { word: "三明治", meaning: "sandwich", example: "我早餐常常吃三明治。(I often eat sandwiches for breakfast.)" },
  { word: "門", meaning: "classifier for subjects/courses", example: "我這學期選了三門課。(I chose three courses this semester.)" },
  { word: "課堂", meaning: "classroom instruction; class session", example: "課堂上不要一直講話。(Don’t keep talking during class.)" },
  { word: "期末", meaning: "end of term; final", example: "期末我有很多考試。(I have many exams at the end of the term.)" },
  { word: "口試", meaning: "oral exam", example: "明天有中文口試。(There is a Chinese oral exam tomorrow.)" },
  { word: "篇", meaning: "measure word for articles/essays", example: "老師要我們寫一篇作文。(The teacher wants us to write an essay.)" },
  { word: "作文", meaning: "composition; essay", example: "這篇作文不太容易。(This essay is not very easy.)" },
  { word: "用功", meaning: "hardworking; diligent (in studying)", example: "他每天都很用功。(He studies diligently every day.)" },
  { word: "當", meaning: "to be (as a job/role)", example: "我將來想當老師。(I want to be a teacher in the future.)" },
  { word: "修", meaning: "to take (a course)", example: "我下學期想修中文會話。(I want to take Chinese Conversation next semester.)" },
  { word: "教授", meaning: "professor", example: "那位教授教得很好。(That professor teaches very well.)" },
  { word: "知識", meaning: "knowledge", example: "他在課堂上學到很多知識。(He learned a lot of knowledge in class.)" },
  { word: "豐富", meaning: "rich; abundant", example: "這本書的內容很豐富。(The content of this book is rich.)" },
  { word: "教法", meaning: "teaching method", example: "老師的教法很特別。(The teacher’s teaching method is special.)" },
  { word: "系", meaning: "department (in a school)", example: "他是中文系的學生。(He is a student in the Chinese department.)" },
  { word: "文法", meaning: "grammar", example: "中文文法不太容易。(Chinese grammar is not very easy.)" },
  { word: "筆試", meaning: "written exam", example: "下週有文法筆試。(There is a grammar written test next week.)" },
  { word: "交", meaning: "to hand in; to submit", example: "請把作業交給老師。(Please hand in your homework to the teacher.)" },
  { word: "報告", meaning: "report; presentation", example: "我們下週要做報告。(We need to give a presentation next week.)" },
  { word: "認真", meaning: "serious; earnest", example: "他做事非常認真。(He does things very seriously.)" },
  { word: "字典", meaning: "dictionary", example: "我常用字典查生詞。(I often use a dictionary to look up new words.)" },
  { word: "翻譯", meaning: "to translate; translation", example: "請把這句話翻譯成中文。(Please translate this sentence into Chinese.)" },
  { word: "翻", meaning: "to look up (in a dictionary/book)", example: "我翻了半天都找不到。(I looked for a long time but still couldn’t find it.)" },
  { word: "題", meaning: "question (on a test/exam)", example: "這一題我不會。(I don’t know how to do this question.)" },
  { word: "努力", meaning: "to work hard", example: "他一直為了考試努力。(He has been working hard for the exam.)" },
  { word: "能力", meaning: "ability", example: "她的中文能力越來越好。(Her Chinese ability is getting better.)" },
  { word: "將來", meaning: "in the future", example: "將來我想去國外工作。(In the future, I want to work abroad.)" },
  { word: "夠", meaning: "enough", example: "時間不夠，請快一點。(There isn’t enough time; please hurry.)" },
  { word: "加油", meaning: "to encourage; to cheer up", example: "明天考試，加油！(The exam is tomorrow — you can do it!)" },
  { word: "義大利", meaning: "Italy", example: "他明年想去義大利旅遊。(He wants to travel to Italy next year.)" },
  { word: "期末考", meaning: "final exam", example: "期末考快到了，你準備好了嗎？(Final exams are coming. Are you ready?)" }
];
